source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PokemonKit_Example' do
  pod 'PokemonKit', :path => '../'
end

target 'PokemonKit_Tests' do
  pod 'PokemonKit', :path => '../'
  pod 'OHHTTPStubs/Swift'
  
end
