source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PokemonKit_Example', :exclusive => true do
  pod 'PokemonKit', :path => '../'
end

target 'PokemonKit_Tests', :exclusive => true do
  pod 'PokemonKit', :path => '../'
  pod 'OHHTTPStubs/Swift'
  
end
