language: objective-c
xcode_project: PromiseKit.xcodeproj
xcode_scheme: [PMKOSX]
xcode_sdk: [macosx10.11]
osx_image: xcode7.3

install:
  - "carthage bootstrap --platform Mac"

matrix:
  exclude:
    - xcode_scheme: PMKOSX
      xcode_sdk: iphonesimulator9.3

branches:
  only:
    - master
    - swift-2.2-minimal-changes
    - swift-2.0-minimal-changes
    - legacy-1.x
